### ISSUE TITLE
508: Focus incorrect on View Comments

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#4836] opened 2023-02-24 18:13 UTC
Issue:
When a user closed the 'View Comments' modal the focus does not return to the button

Steps to Recreate:

- Login to ECMPS, navigate to MP an Select, checkout and open a Configuration
- Click on View Comments and open the modal
- Close the modal and observe that the focus does not return to the View Comments button

**Comment by billmiller13** [comment] 2023-03-07 12:47
Cannot reproduce.  Testing on DEV, the focus returns to the View Comments button as expected when closing the modal.

**Comment by aprematta** [comment] 2023-03-07 19:41
Testing complete, focus now returns to view comments when the modal is closed

**Comment by aprematta** [comment] 2023-03-09 16:50
There's a browser alert that pops up now that says View comments when you close the window..... not sure why that's there...

**Comment by aprematta** [comment] 2023-03-13 12:47
testing complete, focus now returns directly to the view comments button

**Closed as completed by aprematta** 2023-03-13 12:47 UTC
Labels: bug, Emissioners, 508
