### ISSUE TITLE
Bug: Evaluation Stuck in Queue 

### ISSUE THREAD

**Issue by acollad1** [US-EPA-CAMD/PI-1#5555] opened 2023-08-14 21:28 UTC
Steps to Reproduce:

- In ECMPS 2.0, select a configuration and check out the facility
- Import either a QA/QC EDR or a MP
- Navigate to Evaluate and filter on the Facility, Configuration, and Reporting Period (if QA/QC)
- Select the Test Data or MP to evaluate and click the Evaluate button
- BUG è The Eval Status hangs on “In Queue” and the evaluation never completes

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBaFVHIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--1cead6d9e703e2c26adfaf6aaea6a9b43cfd1295/image.png)

**Comment by subrataroyCVP** [comment] 2023-08-18 13:44
Even after multiple try I was unable to reproduce the error. 

Moving it to `Ready for Testing` for Regression Testing

**Comment by mosesdeeCVP** [comment] 2023-08-18 15:51
@mosesdeeCVP

**Comment by mosesdeeCVP** [comment] 2023-08-18 17:39
Was unable to reproduce the bug. Eval never got stuck in Queue after evaluating multiple different facilities and sections.

**Closed as completed by mosesdeeCVP** 2023-08-18 17:39 UTC
Labels: bug, ECMPS Prod Team
