### ISSUE TITLE
Recipient List API

### ISSUE THREAD

**Issue by esaber76** [US-EPA-CAMD/PI-1#6058] opened 2024-01-25 17:44 UTC
Submission confirmation emails are only going to the users performing the submissions. The various ECMPS 2.0 environments need to use the CBS Recipient List API so further testing can be done for ECMPS 2.0 events and emails. The API will return recipient lists for the following actions:

- New stack/pipe monitoring plan submission.
- Submission confirmations.
- Submission reminders.
- Windows notifications.
 
https://camddevelopment.atlassian.net/browse/EASEY-255 includes examples of who should be in the recipient lists to help with testing efforts in 2.0.

**Comment by annalbrecht** [comment] 2024-03-26 19:41
Related to #5826

**Comment by annalbrecht** [comment] 2024-04-05 14:31
Duplicate of #6183.

**Closed as completed by annalbrecht** 2024-04-05 14:31 UTC
Labels: Phase 1, ECMPS, Regression, API, Emails, Jobs, Sprint 1 New Known Issues, Duplicate
