### ISSUE TITLE
MATSDHV-10-B and HOURDHV-24-E errors on already submitted EM data 

### ISSUE THREAD

**Issue by esaber76** [US-EPA-CAMD/PI-1#5990] opened 2023-12-14 21:19 UTC
Found during regression testing in ecmps-tst.app.cloud.gov v2.0.90.

Logged in as saber_ds (Submitter), imported 2023 Q2 emissions from historical for 6071, MS-2A, MS-2B, 2 and evaluated data.

Received multiple MATSDHV-10-B and HOURDHV-24-E errors related to reporting formula IDs for SO2 and SO2RH saying that these formulas are not active in the MP. 

But the formulas are active in the MP. 

<img width="1717" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMEppQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--344ffbb0118b390bafea94dd686f3b8b4463fcf2/Trimble%20County.PNG" alt="Trimble County.PNG" />

**Comment by annalbrecht** [comment] 2024-03-07 14:54
Need to run the file through the check engine and see what happens when you get to those checks. May potentially need to run the file through 1.0 to see what is different.

**Comment by djw4erg** [comment] 2024-08-06 20:27
## Attempted Run In Development Environment

Re-evaluated this emission report in Dev to ensure that the problem still existed before exploring the problem in the debugger, but the problem did not reoccur.

Scott, will check for the problem in Test, where it originally occurred, and if it exists there, I will research the data there and run the Check Engine against Test to determine the cause.

If the problem does not exist in Test, I plan to close this ticket.

**Comment by esaber76** [comment] 2024-08-06 21:17
@djw4erg This is no longer happening in test either.

**Comment by djw4erg** [comment] 2024-08-06 21:20
## Closing Ticket

Closing ticket because Scott and I were not able to recreate the problem in Dev and Test.

**Closed as completed by djw4erg** 2024-08-06 21:20 UTC
Labels: bug, Emissions, Phase 1, ECMPS, Regression, Checks, P-1B, Sprint 1 New Known Issues
