### ISSUE TITLE
View MP Monitoring Method Data from Cloud.gov ECMPS Schema

### ISSUE THREAD

**Issue by karenhwwoo** [US-EPA-CAMD/PI-1#401] opened 2020-11-09 15:34 UTC
As a user I want to view production monitoring plan data in the MP Viewer so that I can look at real time data.

AC
Given a user access the MP viewer
When the Monitoring Method data is displayed
Then the data is pulled from Cloud.gov ECMPS Schema (not the same endpoints as FACT API)

Dependency: Create instance in Cloud.gov, migrate data to new instance

**Comment by david-cvp** [comment] 2020-12-01 16:10
Duplicate of #491

**Closed as completed by david-cvp** 2020-12-01 16:10 UTC
Labels: invalid, Emissioners
