### ISSUE TITLE
Recruit participants

### ISSUE THREAD

**Issue by david-cvp** [US-EPA-CAMD/PI-1#387] opened 2020-11-04 18:38 UTC
Five (5) participants who are familiar/experienced users of Allowance and Compliance data access through Prepackaged Data or the Query Tool.

**Comment by nsameerun** [comment] 2020-12-11 14:38
Compliance and Allowance Data User Study

**Comment by nsameerun** [comment] 2020-12-15 20:17
12/15/2020
**UX Weekly Meeting**

- 5 participants for the study

- EPA (Andrew) primary moderator 

- CVP (Nakia or Stacey) notetakers 

- [ ] EPA (Andrew) will set-up a "Doodle Pool" to confirm the availability of the EPA/CVP team member. 

- [ ] EPA (Andrew) will pre-screen the AMPD user list for potential interview participants. 15-17 ppl on the list.

- [ ] CVP (Caiti) will conduct the final screening for ideal participants and schedule participants into interview slots (date/time). Will Update User Research Interview Tracking Sheet. 
https://docs.google.com/spreadsheets/d/1iGh9aTut9c2GFpLtqfT9T4Noq2iLa-yjd969QXpIZwA/edit?usp=sharing

**Comment by nsameerun** [comment] 2020-12-22 19:48
@areighar @tlageman-epa  @kstetsyuk 

Hey Team! 

Andrew, when you get a moment, can you update this card with the 'Participant Recruitment Update' you gave during our UX Weekly Meeting today? For example, (how many/what type) of participants have been recruited thus far, and how many more we have left to recruit? Also, which weeks in January do you anticipate the interviews to be scheduled based on the doddle pool and participant availability? Please add any information valuable to share with the team on your progress. That way, we have a running record. Thanks a bunch! 

If you prefer, you can cc' me on your emails with Caiti, and I'll be sure to keep this card updated in real-time per the email correspondence.

**Comment by nsameerun** [comment] 2020-12-30 14:40
MS Teams Update: Monday, December 28, 2020 

Andrew: Caiti started scheduling today and already we have 2 out of 5 interviewees confirmed.

**Comment by nsameerun** [comment] 2020-12-30 15:00
https://docs.google.com/spreadsheets/d/1iGh9aTut9c2GFpLtqfT9T4Noq2iLa-yjd969QXpIZwA/edit#gid=170019533

User Research Interview Participant Tracker 

@areighar @tlageman-epa @kstetsyuk

**Comment by nsameerun** [comment] 2020-12-30 16:25
@areighar @tlageman-epa @kstetsyuk 

Update User Research Interview Screener: 

UX Research Interviews confirmed: 

Date: Friday, January 8, 2020

10 AM- (Compliance Agent (Industry) *New Participant
2 PM- (Internal to EPA) *New participant 
3 PM - (Academic / State Agency) *Participated in the prior AMPD Re-engineering user research interviews below: 
(1st- Initial External Stakeholder Interview, 2nd-Large Data Sets and Query Tool using Apportioned Emissions Data Interview)

**Comment by nsameerun** [comment] 2020-12-31 14:46
@areighar @tlageman-epa @kstetsyuk 

Update -User Research Interview Screener:

New UX Research Interview confirmed:

Date: Monday, January 11, 2021
(? Time Missing in Tracker)-Lewis Campbell Broker/Market Analyst) New Participant 

4 out of 5 interviews confirmed to date.

**Comment by nsameerun** [comment] 2021-01-04 21:06
@areighar  @tlageman-epa @kstetsyuk 

5 Scheduled Interviews (dates and times) 

Thursday, January 7, 2021
1pm 

Friday, January 8, 2021
10am
2pm
3pm

Monday, January 11, 2021 
1pm

**Comment by nsameerun** [comment] 2021-01-06 01:40
@areighar @tlageman-epa @kstetsyuk 

01/05/2021 UX Meeting Update:

Due to a schedule conflict on Friday, January 8th, the team will attempt to reschedule Friday's interviews for another date/time. The team will determine primary moderator coverage based on the rescheduling update. 

Progress: 
- Caiti: Aiming to reschedule (Friday, January 8th) interviews (3) @ 10 am, 2 pm, and 3 pm. 
- Andrew: To find the additional time/date for rescheduling the (Friday, January 8th ) interviews, sent Doodle Pool to determine the team's availability for the morning of (Tuesday, January 12th). 

Update:
- One (1) participant moved from (Friday, January 8th @ 3 pm) to (Monday, January 11th @ 3 pm) slot. 
- Two (2) more Friday interviews to reschedule.

**Comment by nsameerun** [comment] 2021-01-11 20:58
The team decided to close this ticket with 4 participants instead of 5. The fifth (5th) participant withdrew last week due to inexperience/familiarity using Allowance and Compliance Data. 
@areighar 
@tlageman-epa 
@kstetsyuk

**Closed as completed** 2021-01-11 20:58 UTC
Labels: Datateers, UX Research
