### ISSUE TITLE
Enhance the data preview to only retrieve applicable filter criteria

### ISSUE THREAD

**Issue by JanellC** [US-EPA-CAMD/PI-1#2304] opened 2021-11-18 15:42 UTC
### Definition of Ready
- [ ] Does this meet the INVEST criteria?
- [ ] Does this have a clearly defined user?
- [ ] Does this have an estimate?
- [ ] Does this have acceptance criteria?
- [ ] Does this have sufficient context for the specific functionality being developed (design, business rules, etc.)
- [ ] Does this have a dev link been provided in the design?
- [ ] Is this traceable to a feature, epic, or PI?

## User Story
As a User 
I want only filterable criteria to be displayed on the data preview
So that I can preview the specific data i am lookign for 

## Acceptance Criteria
Given a User has made a CDD Query with filter criterium 
When the user previews their query 
Then The criteria that is displayed is the available filters 

Given a User has made a CDD Query without any optional filter criterium
When the user previews their query 
Then The criteria that is displayed is the full response 

### Does this Story require 508 Testing?
- [ ] Implementing a new authoring tool that will produce code / content for the application
- [ ] Implementing a 3rd party widget that will be part of the application
- [ ] Adding new / updating custom functionality 
- [ ] Adding new / updating a page template
- [ ] Adding new / replacing existing functionality (unless the replacement has already passed 508 testing)
- [ ] Full Site Review prior to a scheduled EPA 508 review
- [ ] Planning a video that will appear on the application
- [ ] Producing a video that will appear on the application
- [ ] Producing Training materials
- [ ] Producing documents

## Context
(User journeys, design mockups, architectural diagrams, business rules, data element definitions)

During backlog refinement on 11/ 17 team discussed optimizing the data preview by not querying non-applicable filter criteria from the API. It was discussed that this is not a priority  but this enhancement would be added to the backlog for tracking purposes. 

## Testing
Test Case:
Tester:

### Definition of Done
- [ ] Have all Acceptance Criteria been agreed to and validated by the scrum team?
- [ ] Has the code been unit tested and peer reviewed?
- [ ] Have the functional tests been executed?
- [ ] Have all defects been reviewed and dispositioned, resolved, or deferred?
- [ ] Is the user story ready to be deployed to the test/staging environments?

**Comment by hamezene** [comment] 2023-09-28 17:47
@tlageman-epa need more information on what the original requirements.  Can you add steps to recreate and some screen grabs to help us understand how to implement the enhancement?

**Comment by tlageman-epa** [comment] 2023-09-28 17:57
@hamezene this is one ticket that you would need to ask CVP, probably @jwhitehead77 , about. I do not recall and do not understand what is in the context section of this ticket.

**Comment by ergjustin** [comment] 2023-10-05 00:51
@JanellC 
Is this ticket being still valid? If yes, can you please add more information to help us understand how to implement the enhancement?

**Comment by JanellC** [comment] 2023-10-05 13:27
This ticket was written a few years ago and I don't remeber the conversation. Please follow Travis' guidance on this @ergjustin

**Comment by ergjustin** [comment] 2023-10-06 02:45
@tlageman-epa 
I asked Jason and Janell about this ticket, but both don't remember why they open this ticket. This ticket was opened on Nov 18, 2021.
 Is it okay I am closing this ticket?

**Comment by hamezene** [comment] 2023-10-06 12:54
@ergjustin Please go through the steps of filtering data on CAMPD, preview and see if the filters bring up the appropriate criteria selected. 

If there is no issue with the filters on the preview, then i think we are okay to close this ticket.  If the filter is not working as intended; please update this ticket the issue you  found, add screengrabs and steps to recreate and fix the issue. 

Please let me know if you have any questions and we can get on teams.

**Comment by ergjustin** [comment] 2023-10-06 16:51
@hamezene 
I had gone through the steps of filtering data. The filter is working as intended. I was unable to found issue in there. So, I am closing this ticket.

**Comment by hamezene** [comment] 2023-10-06 17:54
Hello Travis,

Please let us know if you are okay with us closing this ticket as Justin has verified the function to be working.

Hiwot Amezene
Program Manager
DecisionPoint Corporation
702 Russell Avenue Suite 312 | Gaithersburg, MD 20877
11911 Freedom Drive Suite 610 | Reston, VA 20190
c: 202-489-2447
***@***.******@***.***>
www.decisionpointcorp.com<http://www.decisionpointcorp.com/>
[A picture containing text, sign  Description automatically generated]
[A picture containing text  Description automatically generated][A picture containing logo  Description automatically generated][Logo  Description automatically generated][Text, logo  Description automatically generated][Text  Description automatically generated]

The contents of this email message and any attachments are confidential and intended solely for the use of the addressee(s) or entity to which they are addressed. If you are not the intended recipient of this message, please notify the sender immediately. If you are not the intended recipient, you are hereby notified that any use, dissemination, copying, or storage of this message or its attachments is strictly prohibited.

**Comment by tlageman-epa** [comment] 2023-10-10 12:47
@ergjustin we can close this ticket. please mark it with the "invalid" label type. thx

**Closed as completed** 2023-10-10 13:49 UTC
Labels: Enhancement, invalid, S, Phase 1, CAMPD
