### ISSUE TITLE
Bug: Global View in BETA Spinner

### ISSUE THREAD

**Issue by acollad1** [US-EPA-CAMD/PI-1#5896] opened 2023-11-07 18:26 UTC
Issue:
In BETA Global View The blue wheel kept spinning in trying to load a "204 no content data" into a view template.
Steps to Recreate:
1. Go to Global view
2. Selec Limestone config LIMI1
3. Select 2023 Q2 Reporting Period
4. Select Hourly NOx Mass CEM View

**Comment by subrataroyCVP** [comment] 2023-11-08 02:59
Unable to reproduce the issue. Moving this for testing.

**Comment by mosesdeeCVP** [comment] 2023-11-08 21:25
@mosesdeeCVP

**Comment by mosesdeeCVP** [comment] 2023-11-08 21:39
Getting proper error after no data is found

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMHE1QVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--2ab7c84af21aa52589a20afacbfc3cc3b76d3e2c/Global%20View%20in%20BETA%20Spinner%20%235896%20Error%20after%20spinner.png)

**Comment by mosesdeeCVP** [comment] 2023-11-08 21:44
In the Test environment I am able to reproduce this bug where the blue spinner keeps spinning for an extended period of time. Then the user sees the message from in the above screenshot

**Comment by mosesdeeCVP** [comment] 2023-11-08 21:46
Was unable to reproduce this error in the Beta environment because "Hourly NOx Mass CEM" does not exist in the dropdown for 2023 Q2 Reporting Period.

**Comment by subrataroyCVP** [comment] 2023-11-14 16:36
There are some refactor work needs to be done for `Hourly NOx Mass CEM View`, Because of that refreshing of views is not working correctly. This needs to tested/verify after the refactor work completes.

**Comment by esaber76** [comment] 2024-02-22 16:04
Confirm if this is still an issue.

**Comment by mxtomoto1** [comment] 2024-04-08 13:58
On Beta, attempting the above steps first leads to the errors up top in the attached screenshot. Selecting the Hourly NOx Mass CEM View a second time seemed to have loaded the data properly.
<img width="928" alt="t_d1" src="https://github.com/US-EPA-CAMD/easey-ui/assets/94564355/bc04a93d-de73-4307-ad45-07dbde5a1161">

**Comment by annalbrecht** [comment] 2024-04-09 17:12
After today's push to Beta, this appears to be working.

**Closed as completed by annalbrecht** 2024-04-09 17:12 UTC
Labels: bug, Emissions, Phase 1, ECMPS
