### ISSUE TITLE
Bug: Issue with End Date Validation for MATS

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#5027] opened 2023-03-30 15:53 UTC
Issue:
When a user wishes to create or edit a MATS (Supplemental Methods) record, and picks either the End Date or Time only, then the system closes the modal and displays an error message on the Configurations screen. The validation should be displayed inside the modal and when the user makes the updates accordingly, should save the updates

Steps to Recreate:
1. Login to ECMPS and access the MP Module
2. Select and open a Configuration and check it out
3. Select Methods from the Sections dropdown and click Create MATS
4. Enter all the information as needed and enter only the End Date or End Time and click Create/Save and Close
You will notice that the modal is closed and the validation is displayed on the configurations screen

**Comment by billmiller13** [comment] 2023-04-05 12:40
I could not reproduce this error.  Validation checks give error messages and force you to enter both End Date and End Time if either of this fields is not null.

**Comment by billmiller13** [comment] 2023-04-06 12:38
This was already fixed by Robert - see US-EPA-CAMD/easey-ecmps-ui PR #995

**Comment by mosesdeeCVP** [comment] 2023-04-06 19:02
Bug fixed. Errors work as expected

**Closed as completed** 2023-04-06 19:07 UTC
Labels: bug, Emissioners, EPRI
