### ISSUE TITLE
componentRecordId in MP Exports

### ISSUE THREAD

**Issue by lgiannini1** [US-EPA-CAMD/PI-1#6182] opened 2024-03-22 13:09 UTC
When exporting a monitoring plan in the public view and workspace, there is an additional componentRecordId element included in the monitoringSystemComponentData records. This ID is the component_id for the component from the camd_ecmps.monitor_system_component table. 

![Image](https://github.com/US-EPA-CAMD/easey-ui/assets/63416419/cc659b4f-d6d6-43dd-afdb-71151107796a)

**Comment by annalbrecht** [comment] 2024-03-25 14:24
Lane will inventory the other file types to see if there are other instances that need to be fixed.

**Comment by lgiannini1** [comment] 2024-03-27 16:57
QA Data record exports reviewed from dev:

- [ ] AppE - Summary record contains id, testSumId, userId, addDate, and updateDate elements. Run data records contain id, appECorrTestSumId, userId, addDate, and updateDate elements. These elements are only present in the export if it is created while logged in. (example export: [QA & Certification Export - A B Brown Generating Station .json](https://github.com/US-EPA-CAMD/easey-ui/files/14791983/QA.Certification.Export.-.A.B.Brown.Generating.Station.json)) 
- [ ] AppE Heat Input from Gas - Contains id, appECorrTestRunId, userId, addDate, and updateDate elements. These elements are only present in the export if it is created while logged in.
- [ ] AppE Heat Input from Oil - same issue as AppE Heat Input from Gas records. These elements are only present in the export if it is created while logged in.
- [ ] Air Emissions - Contains an id, testSumId, userId, addDate, and updateDate element from RATA, Unit Default, and Appendix E export. These elements are only present in the export if it is created while logged in. (example can be seen in export above)
- [x] 7 Day Calibration 
- [x] Cycle Time
- [x] Linearity
- [x] Mercury Linearity
- [x] RATA
- [x] RATA (Flow)
- [x] Flow to Load Check
- [x] Flow to Load Reference
- [x] Fuel Flow to Load Test
- [x] Fuel Flow to Load Baseline
- [x] Fuel Flowmeter Accuracy
- [x] Online/ Offline Calibration
- [x] Unit Default Test
- [x] Transmitter/ Transducer 
- [x] Protocol Gas
- [x] Test Qualification
- [x] Cert Event
- [x] TEE

EM Data record exports reviewed from dev:

- [x] Summary Value
- [x] Weekly Test Summary
- [x] Weekly System Integrity
- [x] Daily Test Summary
- [x] Daily Calibration
- [x] Hourly Operating
- [x] Monitor Hourly Value
- [x] MATS Monitor Hourly Value
- [x] MATS Derived Hourly Value
- [x] Derived Hourly Value
- [x] Hourly Fuel Flow
- [x] Hourly Parameter Fuel Flow
- [x] Hourly GFM
- [x] LTFF
- [x] Sampling Train
- [x] Sorbent Trap
- [x] NSPS4T Summary
- [x] NSPS4T Compliance
- [x] NSPS4T Fourth Quarter

**Comment by alangmaid** [comment] 2024-06-07 17:41
This is a duplicate of #6223

**Closed as completed by alangmaid** 2024-06-07 17:41 UTC
Labels: MP, Phase 1, ECMPS, Sprint 1 New Known Issues
