### ISSUE TITLE
Limit Facilities to Logged in User 

### ISSUE THREAD

**Issue by JorjaComer** [US-EPA-CAMD/PI-1#478] opened 2020-11-25 17:52 UTC
## User Story
As a user
I want to see facilities assigned to me 
So that I can view all monitoring plans for all facilities I manage 

## Acceptance Criteria
Given
When
Then

## Context
EPA will need to determine how this will happen in conjunction with CDX (roles) and CBS (org/facility)

## Testing
Test Case:
Tester:

### Issue Requester:
Requester:

**Comment by karenhwwoo** [comment] 2021-05-25 19:06
Duplicate of #1410

**Closed as completed by karenhwwoo** 2021-05-25 19:06 UTC
Labels: Emissioners
