### ISSUE TITLE
RETEST: QA Add/Edit modal of RATA data 

### ISSUE THREAD

**Issue by acollad1** [US-EPA-CAMD/PI-1#5909] opened 2023-11-16 14:14 UTC
Issue: Add/Edit modal of RATA data has RATA Frequency Code dropdown where the populated values do not seem to all be appropriate, hence user can't provide/select a value.

**Comment by jwhitehead77** [comment] 2023-11-21 22:44
Cannot reproduce the dropdown issue all codes are coming back. 

Reporting Instructions
![image](https://github.com/US-EPA-CAMD/easey-ui/assets/66504934/63239774-c81b-4132-a9e5-470c0b55fb5d)

Database
![image](https://github.com/US-EPA-CAMD/easey-ui/assets/66504934/5d9f8271-e844-45d0-8852-fe8a5fc92233)

UI Screen
![image](https://github.com/US-EPA-CAMD/easey-ui/assets/66504934/78f2ff49-e7f2-437c-aba0-03aa6c460253)

I was able to save for 2 Quaters, 4 Quarters, & Ozone Season.

Saving with 8 Quarters gets this error...
![image](https://github.com/US-EPA-CAMD/easey-ui/assets/66504934/1de96e53-8d60-4879-a961-a68d16239a33)

Saving with Alt Single-Load Flow gets this error...
![image](https://github.com/US-EPA-CAMD/easey-ui/assets/66504934/b45654a1-bf8d-4edc-90a2-8a4ea3dc69b2)

The errors above are correct based on the System data and and checks...
![image](https://github.com/US-EPA-CAMD/easey-ui/assets/66504934/18debf9d-7c91-43ef-aa7c-d4bd58758382)
![image](https://github.com/US-EPA-CAMD/easey-ui/assets/66504934/927a875e-295f-463f-8a35-2cac8441dbf9)

**Comment by lgiannini1** [comment] 2024-04-04 16:18
Not able to reproduce this issue on dev and tst with ORIS 7900, SH1 test number RATA-Q32023-NOX-1. List of RATA Frequency Codes looks correct in dropdown. Moving this ticket to done.

**Closed as completed by lgiannini1** 2024-04-04 16:18 UTC
Labels: bug, QA, ECMPS Prod Team, Phase 1, ECMPS
