### ISSUE TITLE
Reseach - "Create Test Script to Import/Export all MP" 

### ISSUE THREAD

**Issue by spetros-do** [US-EPA-CAMD/PI-1#6020] opened 2023-12-27 16:13 UTC
Context
Create scripts to identify issues with import/export in ECMPS. Jason W. has started some of the work for this. The work Jason has completed is in the EASEY task runner repo. https://github.com/US-EPA-CAMD/easey-task-runner
On 10/18, it was decided that Jason will stop working on this and DPC will looking into contuing the work

Requirements
- Shall create a script that exports clean files from all of the facilities and then successfully imports the files back into the system.
- The script shall have the ability to log errors. This should capture what file failed/when it failed/ why it failed.
- Can execute this by creating a task runner or a cron job
- Can log errors using kibanna or splunk
- Next Steps: need to have further technical design discussion on how to implement this

----```
Use this issue template when creating a new user research epic - each line below is an issue to be added under the epic.
```

## Study Steps
Design and develop user research study
Develop moderator's guide
Recruit participants
Conduct interviews
Analyze research findings
Prepare high level executive summary

**Comment by annalbrecht** [comment] 2024-03-29 17:45
Closing this as a duplicate of #5571/#6021.

**Closed as completed by annalbrecht** 2024-03-29 17:45 UTC
Labels: UX Research, MP, Phase 1, ECMPS, P-1B, Sprint 1 New Known Issues, Duplicate
