### ISSUE TITLE
Slow response in swagger page for 5092 and 5093

### ISSUE THREAD

**Issue by alangmaid** [US-EPA-CAMD/PI-1#5855] opened 2023-10-27 15:00 UTC
Am able to get requests to perform successfully in the swagger page while testing in staging but it is slow and threw the browser unresponsive warning. 

https://app.zenhub.com/workspaces/dpcerg-scrum-board-5f36cc8dfed6db0022b0f4db/issues/gh/us-epa-camd/easey-ui/5092

https://app.zenhub.com/workspaces/dpcerg-scrum-board-5f36cc8dfed6db0022b0f4db/issues/gh/us-epa-camd/easey-ui/5093
```[tasklist]
### Tasks
```

**Comment by shahbazkhan1999** [comment] 2024-01-18 20:32
Hi @alangmaid,  I have confirmed that the ticket is functioning correctly on staging; however, the issue only arises in the Dev environment. It's worth noting that we refrain from deploying changes to the Dev environment, as it is exclusively reserved for ECMPS.

**Comment by shahbazkhan1999** [comment] 2024-01-18 20:32
Hi @alangmaid,  I have confirmed that the ticket is functioning correctly on staging; however, the issue only arises in the Dev environment. It's worth noting that we refrain from deploying changes to the Dev environment, as it is exclusively reserved for ECMPS.

**Comment by alangmaid** [comment] 2024-03-14 20:36
@shahbazkhan1999 is there anything a UI tester can test to confirm this ticket OR can we consider this complete?

**Comment by alangmaid** [comment] 2024-03-19 13:52
Linked to #5092 and #5093 
The swagger pages in the above tickets need to be tested on STAGING to ensure that the response times are reasonable.

**Comment by szintgraff** [comment] 2024-03-29 15:26
Tested in staging and not seeing the issue resolved. Was this pushed to staging? It looks like the issue is resolved in dev.

**Comment by lgiannini1** [comment] 2024-03-29 16:23
@szintgraff I was able to make requests on the staging emissions management swagger page (https://api.epa.gov/easey/staging/emissions-mgmt/swagger/#/Apportioned%20Quarterly%20Emissions/QuarterlyApportionedEmissionsController_getEmissions) that was mentioned in #5092 and through Postman

**Comment by szintgraff** [comment] 2024-03-29 16:26
@lgiannini1 I believe the error is on the streaming services page: https://api.epa.gov/easey/staging/streaming-services/swagger/#/Apportioned%20Quarterly%20Emissions/QuarterlyApportionedEmissionsController_streamEmissions

**Comment by lgiannini1** [comment] 2024-03-29 17:49
@szintgraff Ah, my mistake. I am seeing the same slowdown on staging but not dev. The dev streaming services page is also has a more recent publish date than staging I noticed. @shahbazkhan1999 will investigate.

**Comment by lgiannini1** [comment] 2024-04-01 16:01
Making API calls in Postman and from the CAMPD Custom Data Download -> Emissions, Quarterly Emissions, Unit (No Aggregation) both work successfully on staging. Moving this ticket to done.

**Closed as completed by lgiannini1** 2024-04-01 16:01 UTC
Labels: Phase 1, CAMPD, v1.4 Release
