### ISSUE TITLE
Sonar Cloud Bug: ECMPS UI 

### ISSUE THREAD

**Issue by acollad1** [US-EPA-CAMD/PI-1#5656] opened 2023-09-13 15:50 UTC
- [ ] Remediate sonar cloud bug in ECMPS UI 
https://sonarcloud.io/organizations/us-epa-camd/projects

- [ ] Resolving promises reference:
promises.push( new Promise((resolves, rejects) => {}) ) -> Needs to become promises.push(async function signature)

**Comment by shahbazkhan1999** [comment] 2023-09-29 15:27
@ergjustin and @subrataroyCVP  will review PR

**Comment by shahbazkhan1999** [comment] 2023-10-05 20:51
76 unit tests are failed first need to resolve them to solve sonar cloud bugs @tlageman-epa @jwhitehead77

**Comment by shahbazkhan1999** [comment] 2023-10-05 20:51
76 unit tests are failed first need to resolve them to solve sonar cloud bugs @tlageman-epa @jwhitehead77

**Comment by shahbazkhan1999** [comment] 2023-10-09 13:09
@acollad1 please make a ticket for test cases and assign to the concerned developer.

**Comment by shahbazkhan1999** [comment] 2024-02-02 15:22
Here is the PR for the failed test cases and @spetros-do will do peer review
https://github.com/US-EPA-CAMD/easey-ecmps-ui/pull/1395

**Comment by annalbrecht** [comment] 2024-03-13 14:27
@shahbazkhan1999 Please add additional information about what the tester needs to look at.

**Comment by shahbazkhan1999** [comment] 2024-03-13 16:19
There are two ways to test this ticket the first and easiest one is to go to GitHub actions if there is no error on the Unit test section it means all tests are successful here is the link for that : [https://github.com/US-EPA-CAMD/easey-ecmps-ui/actions/runs/8267654025/job/22618603295?pr=1400](URL) 
the other way that you can run all the tests locally because this is something related to code so you can run the command (yarn run test) in a specific repo to check if all test cases are successful lemme attached a screenshot that test cases run successfully 

Here is the screenshot of GitHub :

![Image](https://github.com/US-EPA-CAMD/easey-ui/assets/136729393/586f4138-94f4-4d92-b509-d02fe73e89bf)

**Comment by lgiannini1** [comment] 2024-03-25 14:46
@shahbazkhan1999 The pull requests linked on this ticket are still open and have not been merged to dev. Also Sonarcloud is showing that this pull request https://github.com/US-EPA-CAMD/easey-ecmps-ui/pull/1400 is not merged.



![Image](https://github.com/US-EPA-CAMD/easey-ui/assets/63416419/799c34ab-c37e-49d9-971c-b6aed696c97d)

**Comment by j-tafoya** [comment] 2024-03-26 19:43
Look like there are several requests for changes on the PR, this should move back to QA In Progress or elsewhere?

**Closed as completed** 2024-04-25 13:32 UTC
Labels: bug, Phase 1, ECMPS

**Comment by mark-hayward-erg** [comment] 2024-04-25 13:34
Remaining broken tests have been fixed.  Changes to actual code files will be covered by other testing, including an in depth regression testing effort for the typeORM changes (#6185 )
