### ISSUE TITLE
508 Issue: QA module 508 modifications 

### ISSUE THREAD

**Issue by JanellC** [US-EPA-CAMD/PI-1#4513] opened 2022-11-18 16:19 UTC
## Context 

All tables reviewed have the data cells with a role of gridcell instead of cell which breaks the association to the table headers. The scope of this ticket is to make the update for all levels of nesting for the following Test Types: App E, Calibration Injection, Flow to Load Check, Fuel Flow to Load, Fuel Flow to Load Baseline, Linearity Summary, Online Offline Calibration, Relative Accuracy

**Comment by aprematta** [comment] 2022-11-30 21:31
All tables were good except the Fuel flow to load type - both main and sub tables still had gridcell

**Comment by subrataroyCVP** [comment] 2022-12-01 03:26
I am not able to see that issue with the test-type you mentioned. Could you please explain , so I can reproduce and resolve the issue.

**Comment by aprematta** [comment] 2022-12-01 15:45
Looks like it's cell now. I went through all and rechecked. I have noticed sometimes that it will go back to gridcell. Will keep an eye out for this for next sweep of the site but closing ticket for now.

**Closed as completed by aprematta** 2022-12-01 15:45 UTC
Labels: bug, Emissioners, 508
