### ISSUE TITLE
Error in filename for Monitoring Plan export

### ISSUE THREAD

**Issue by maheese** [US-EPA-CAMD/PI-1#6222] opened 2024-04-25 13:31 UTC
When I export any monitoring plan the file name that appears is missing the configuration and displays "undefined".

![Image](https://github.com/US-EPA-CAMD/easey-ui/assets/16920772/10d3b2dd-858f-4e68-bbca-8d936d18959a)

**Comment by annalbrecht** [comment] 2024-04-25 20:56
Duplicate of #5983

**Closed as completed** 2024-04-25 20:56 UTC
Labels: bug, MP, Phase 1, ECMPS, Sprint 3 New Known Issues
